config/routes.rb
Rails.application.routes.draw do
resources :users
resources :beverages do 
  resources :colors
end

resources :designs
resources :votes

resource :session, only: [:new, :create, :destroy ]

  root 'beverages#index'

end

app/models/beverage.rb
class Beverage < ActiveRecord::Base

belongs_to :user
has_many :votes
has_many :colors
accepts_nested_attributes_for :colors


end

app/models/color.rb
class Color < ActiveRecord::Base

belongs_to :beverage

end

app/models/design.rb
class Design < ActiveRecord::Base

belongs_to :beverage
belongs_to :user
has_many :votes 
has_many :colors
accepts_nested_attributes_for :colors

end

app/models/trinket.rb
class Trinket < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password 

has_many :beverages
has_many :votes


validates_presence_of :name
validates_presence_of :email
validates_uniqueness_of :email
validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/models/vote.rb
class Vote < ActiveRecord::Base

belongs_to :beverage



state_machine :state, :initial => :unassigned do 
	state :unassigned
	state :positive
	state :negative
	state :meh
	state :flagged

event :love do 
	transition all => :positive 
end

event :whatev do 
	transition all => :meh
end

event :hate do
	transition all => :negative
end

event :flag  do 
	transition all => :flagged
end
end
	
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


helper_method :current_user
  
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end


end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  def index
    @beverages = Beverage.paginate(:page => params[:page], :per_page => 3)
    @votes = Vote.new
  end

  def new
    @user = User.find(current_user.id)
    @beverage = @user.beverages.new
    3.times {@beverage.colors.build}


  end

  def create
    @user = User.find(current_user.id)
    @beverage = @user.beverages.new(beverage_params)


    if @beverage.save
      redirect_to beverages_path
    else
      render 'new'
    end
  end

  def show
    @beverage = Beverage.find(params[:id])
    @votes = @beverage.votes
    # gon.watch.bevId = @beverage.id 
    # gon.watch.jbuilder
    gon.watch.positive = @votes.where(state: 'positive').count
    gon.watch.negative = @votes.where(state: 'negative').count
    gon.watch.meh = @votes.where(state: 'meh').count

  end

  def edit
    @beverage = Beverage.find(params[:id])

  end

  def destroy
  end

  def update
    @beverage = Beverage.find(params[:id])
    if @beverage.update(beverage_params)
      redirect_to beverages_path
    else
      render 'edit'
    end
  end

private
  def beverage_params
    params.require(:beverage).permit(:name, colors_attributes:[:id, :name, :value])
  end

end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def index
    @colors = Color.all
  end

  def new
    @beverage = Beverage.all
    @color = Color.new
  end

  def create
    @beverage = Beverage.all
    @color = Color.new(color_params)
    if @color.save
      redirect_to colors_path
    else
      render 'new'
    end
  end

  def edit
    @color = Color.find(params[:id])

  end

  def destroy
  end

  def update
    @color = Color.find(params[:id])
    if @color.update(color_params)
      redirect_to colors_path
    else
      render 'edit'
    end
  end

private
  def color_params
    params.require(:color).permit(:name, :value)
  end


end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController

def index
	@designs = Design.all


end

def show
	@design = Design.find(params[:id])	
	@vote = Vote.create_with(@design.id)
end


def new
	@design = Design.new
end

def create

	@user = User.find(current_user.id)

	@design = @user.designs.new(design_params)


	if @design.save
		redirect_to designs_path
	else
		render 'new'
	end

end

def edit
end

def update
end

def destroy
end

private 
def design_find
	@design = Design.find(params[:id])	
end

def design_params
	params.require(:design).permit(:name, :format, :beverage_id)
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
	@user = User.new
	@is_login = true
end

def create
	# find user
	u = User.find_by(email: params[:user][:email])

	# match them to their password
	if u && u.authenticate(params[:user][:password])
		session[:user_id] = u.id.to_s
		redirect_to user_path(u.id)
	else
		redirect_to new_session_path
	end
end

def destroy
	reset_session
	redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new

  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end

  end

  def show
    @user = User.find(params[:id])
    @beverages = Beverage.where(user_id: @user).paginate(:page => params[:page], :per_page => 4)
    gon.watch.beverageTally = Beverage.where(user_id: @user).count
  end

  def edit
  end

  def destroy
  end

  def update
  end

private
  def user_find
    @user = User.find(params[:id])

  end
  def user_params
    params.require(:user).permit(:name, :type, :email, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

def index
	@votes = Vote.all
end


def new
	@design = Design.find(params[:id])
	@vote = @design.votes.new
end

def create
	@beverages = Beverage.all
    @vote = Vote.new(vote_params)


    if @vote.save
      redirect_to beverages_path
    else
      render 'new'
    end
end


private
def vote_params
	params.require(:vote).permit(:state, :user_id, :beverage_id)
end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper




end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beverages/create.html.erb
<h1>Beverages#create</h1>
<p>Find me in app/views/beverages/create.html.erb</p>

app/views/beverages/destroy.html.erb
<h1>Beverages#destroy</h1>
<p>Find me in app/views/beverages/destroy.html.erb</p>

app/views/beverages/edit.html.erb
<h1>Beverages#edit</h1>
<p>Find me in app/views/beverages/edit.html.erb</p>

app/views/beverages/index.html.erb
<div class="container">

<div class="bev-logo">
<!-- the logo goes here. loads in CSS -->
</div>

<% @beverages.each do |b| %>
<!-- create svg cans on the fly using rails -->

<div class="col-md-4">
<div class="bev-contain">




<svg id="can" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 viewBox="0 0 960 560" >
	 <g>
<polygon fill=<%=b.colors[0].value %> points="344.7,89.8 413.2,148.2 413.2,516.3 344.7,456 "/>
<polygon fill=<%=b.colors[2].value%> points="547.9,148.9 612.9,90.9 612.9,454.9 547.9,516.2 "/>
<rect fill=<%=b.colors[1].value %>  x="412" y="148.2" width="137" height="368"/>
<polygon opacity="0.25" fill="#FFFFFF" enable-background="new    " points="344.8,193.1 413.1,179.3 548.5,179.3 613.1,167.9 
	613.1,157.1 548.5,168.6 413.1,168.6 344.8,182.4 "/>
<rect x="378.9" y="57.1" transform="matrix(0.776 -0.6307 0.6307 0.776 39.3807 284.1144)" width="81.6" height="59.1"/>
<rect x="451.3" y="60.7" fill="#C6C6C6" width="37.3" height="41.3"/>
<path fill="#939393" d="M547,31.3H412.6l-68.1,58.9l68.9,58.7H548l65.1-58.1L547,31.3z M403.8,113.2l-26.4-21.5l75-27.6l26.4,22.5
	L403.8,113.2z"/>
<polygon opacity="0.25" fill="#FFFFFF" enable-background="new    " points="344.6,443.8 413,412.7 548.3,412.7 612.9,386.7 
	612.9,362.5 548.3,388.4 413,388.4 344.6,419.5 "/>
	</g>
</svg>


<div class="bev-names">

	<h2><%= link_to b.name, beverage_path(b.id)  %></h2>
			<h3><span class="label label-success"><%= Vote.where(beverage_id: b.id, state: "positive").count %></span>
			<span class="label label-default"><%= Vote.where(beverage_id: b.id, state: "meh").count %></span>
			<span class="label label-danger"><%= Vote.where(beverage_id: b.id, state: "negative").count %></span></h3>

<% if current_user != nil %>
<% if Vote.where(beverage_id: b.id, user_id: current_user.id ).first == nil %>
	<%= form_for Beverage.where(id: b.id).first.votes.new do |f| %>
		<%= f.select :state,[['love', :positive ], ['meh',:meh], ['bad', :negative]]%>
		<%= f.hidden_field :beverage_id, :value => b.id %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
		<%= f.submit %>
	<% end %>
<% end %>
<% end %>
</div>
</div>
</div>


<% end %>



</div>
<div class="row">
<div class="pager">
<h2><%= will_paginate @beverages, :next_label => ">", :previous_label => "<", :link_separator => " " %>
<% if current_user != nil %>
<h2 class="pagination"><%= link_to "+ Beverage", new_beverage_path %></h2>
<% end %>
</div>

app/views/beverages/new.html.erb
<div class="container">


<div class="jumbotron">

<%= bootstrap_form_for @beverage do |f|%>
<div class="col-md-8">
<h1> New Beverage </h1>
<p><%= f.text_field :name, placeholder: "Name", label: "Beverage Name" %></p>
<!-- create associated colors -->
</div>
<div class="col-sm-4">
<h3>Colors for Beverage </h3>
<%= f.fields_for :colors do |color|%>

<%= color.color_field :value, label: "_" %> 

<% end %>
</div>

<%= f.submit %>
<% end %>


</div>


</div>


<div class="back-button">

<h2><%= link_to "Back", beverages_path %> </h2>
</div>

app/views/beverages/show.html.erb
<div class="container">

<!-- build an svg -->
<div class="col-md-6 bev-contain">

	<svg version="1.1" id="can" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
		 viewBox="0 0 960 540" >
		 <g>
	<polygon fill=<%=@beverage.colors[0].value %> points="344.7,89.8 413.2,148.2 413.2,516.3 344.7,456 "/>
	<polygon fill=<%=@beverage.colors[2].value%> points="547.9,148.9 612.9,90.9 612.9,454.9 547.9,516.2 "/>
	<rect fill=<%=@beverage.colors[1].value %>  x="412" y="148.2" width="137" height="368"/>
	<polygon opacity="0.25" fill="#FFFFFF" enable-background="new    " points="344.8,193.1 413.1,179.3 548.5,179.3 613.1,167.9 
		613.1,157.1 548.5,168.6 413.1,168.6 344.8,182.4 "/>
	<rect x="378.9" y="57.1" transform="matrix(0.776 -0.6307 0.6307 0.776 39.3807 284.1144)" width="81.6" height="59.1"/>
	<rect x="451.3" y="60.7" fill="#C6C6C6" width="37.3" height="41.3"/>
	<path fill="#939393" d="M547,31.3H412.6l-68.1,58.9l68.9,58.7H548l65.1-58.1L547,31.3z M403.8,113.2l-26.4-21.5l75-27.6l26.4,22.5
		L403.8,113.2z"/>
	<polygon opacity="0.25" fill="#FFFFFF" enable-background="new    " points="344.6,443.8 413,412.7 548.3,412.7 612.9,386.7 
		612.9,362.5 548.3,388.4 413,388.4 344.6,419.5 "/>
		</g>
	</svg>

<div class="col-md-12 bev-user">

<!--This is the "beverage master" who says his opinion about the design -->
<h1> THIS BEVERAGE 
<!--logic to compare positive to negative to neutral votes -->
	<% if Vote.where(beverage_id: @beverage.id, state: "positive").count > 
		Vote.where(beverage_id: @beverage.id, state: "negative").count %>
			IS AWESOME
	<% elsif Vote.where(beverage_id: @beverage.id, state: "positive").count == 
		Vote.where(beverage_id: @beverage.id, state: "negative").count %>
			IS OK
	<% else %>
			SUCKS
	<% end %>
</h1>
</div>

	<div class="back-button">

		<h3><%= link_to "Back", beverages_path %></h3>

	</div>

</div>
	
	<div class="col-md-6 jumbotron">
		<div class="bev-names">
				<h2><%= @beverage.name %></h2>
				<h4>By <%= link_to User.find(@beverage.user_id).name, user_path(@beverage.user_id) %></h4>
		</div>
	
		<div id="piechart" class="bev-contain">
		<!-- Piechart loads here, as well as boxes that show vote distribution -->
			<h3>
				<div href="#" class="label label-success">
					<%=image_tag "check.svg", size:"20x20" %> <%= Vote.where(beverage_id: @beverage.id, state: "positive").count %>
				</div>

				<div href="#" class="label label-default">
					 <%= image_tag "dash.svg", size:"20x20" %> <%= Vote.where(beverage_id: @beverage.id, state: "meh").count %>
				</div>

				<div href="#" class="label label-danger">
					 <%=image_tag "x.svg", size:"20x20" %> <%= Vote.where(beverage_id: @beverage.id, state: "negative").count %>
				</div>
			
			</h3>
			
		</div>
</div>

<!--This tag is necessary to push the values into javascript. don't tell -->
<%= include_gon %>


<script type="text/javascript">


// pops in the can on mouseover to show colors. using the snap.svg JS library.
// rails isnt happy with it, because you say require snap.svg and its all "dafuq u doin boi, u no require an svg here son"

var s = Snap("#can");
var g = s.select("g");
//animates the can on mouse over.
 g.mouseover(  function() { g.animate({ transform: 's3r3,6,5' }, 1000, mina.bounce ) } );
// animates can on mouse out.
 g.mouseout	(  function() { g.animate({ transform: 's1r0,150,150' }, 1000, mina.bounce ) });

// Dataset for pie chart. the gon gem is like listening to Miley Cyrus.  Its some catchy stuff, but not
// easy to admit to.

var dataset = {
// positive votes(green), meh votes (grey), negative votes (red). defined in the beverages controller.
  states: [gon.positive, gon.meh, gon.negative]
};

var width = 460,
    height = 300,
    radius = Math.min(width, height) / 2;

// color range for pie chart. this pops each variable to a specific color.
var color = d3.scale.ordinal()
    .range(["#3ab936", "#5d5d5d",  "#ff2316"]);

// i love pie
var pie = d3.layout.pie()
    .sort(null);

// sets the inner donut hole and outer radius
var arc = d3.svg.arc()
    .innerRadius(radius - 75)
    .outerRadius(radius - 40);

// i don't really love pie, but pie charts are cool. create pie chart here.
var svg = d3.select("#piechart").append("svg")
    .attr("width", width)
    .attr("height", height)
    .append("g")
    .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

// append the pie to put the data in it. sort of like appending the crust to put the filling in it. just a lot less tasty.
// also the attrTween pops in the data in a slick animation.
var path = svg.selectAll("path")
    .data(pie(dataset.states))
  .enter().append("path")
    .attr("fill", function(d, i) { return color(i); })
    .transition().delay(function(d, i) { return i * 800; }).duration(800)
  .attrTween('d', function(d) {
       var i = d3.interpolate(d.startAngle, d.endAngle);
       return function(t) {
           d.endAngle = i(t);
         return arc(d);
       }
  });


// script closes here. just so you know. I don't really like pie.
</script>

app/views/beverages/update.html.erb
<h1>Beverages#update</h1>
<p>Find me in app/views/beverages/update.html.erb</p>

app/views/colors/index.html.erb
<style>
.colorSwatch {
	width: 100px;
	height: 100px;
}


</style>

<h1>Color Selects</h1>

<% @colors.each do |color| %>
<%= color.name %>
<div class="colorSwatch" style="background-color:<%= color.value %>"></div>
<% end %>

app/views/colors/new.html.erb
<%= form_for @color do |c|%>
<%= c.text_field :name, placeholder: "Name" %>
<%= c.color_field :value %> Hex Value Color - include #
<%= c.submit %>
<% end %>

app/views/designs/index.html.erb
Design Index

show all designs?


<% @designs.each do |design| %>
<div class="col-md-3">
<h3><%= link_to design.name, design_path(design) %></h3>
<p><%= Beverage.find(design.beverage_id).name %></p>
<p> by <%= User.find(design.user_id).name %> </p>


</div>
<% end %>

app/views/designs/new.html.erb
<%= form_for @design do |f| %>
<%= f.text_field :name, placeholder: "Name"%>
<%= f.collection_select :beverage_id, Beverage.all, :id, :name %>
<%= f.submit %>
<% end %>

app/views/designs/show.html.erb
<%= @design.name %>
<% @design.votes.each do |v| %>
<%= v.state %>
<% end %>

<%= @vote.each do |f| %>

<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container jumbotron">
<div class="col-md-4">
<h1> Sign Up</h1>
</div>
	<div class="col-md-8">
		<%= bootstrap_form_for @user do |f|%>
		<%= f.text_field :name, placeholder:"your name" %>
		<%= f.text_field :email, placeholder:"your email (don't worry we wont spam you)" %>
		<%= f.password_field :password, placeholder:"password" %>
		<%= f.password_field :password_confirmation, placeholder:"type that password again" %>
		<%= f.submit %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">


<!-- the logo goes here. loads in CSS -->
	<div class="bev-user">
		<h1><%=@user.name %>'s Beverages</h1>
	</div>


<% @beverages.each do |b| %>
<!-- create svg cans on the fly using rails -->

	<div class="col-md-3">
		<div class="bev-contain">
			<svg id="can" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
				 viewBox="0 0 960 560" >
				 <g>
			<polygon fill=<%=b.colors[0].value %> points="344.7,89.8 413.2,148.2 413.2,516.3 344.7,456 "/>
			<polygon fill=<%=b.colors[2].value%> points="547.9,148.9 612.9,90.9 612.9,454.9 547.9,516.2 "/>
			<rect fill=<%=b.colors[1].value %>  x="412" y="148.2" width="137" height="368"/>
			<polygon opacity="0.25" fill="#FFFFFF" enable-background="new    " points="344.8,193.1 413.1,179.3 548.5,179.3 613.1,167.9 
				613.1,157.1 548.5,168.6 413.1,168.6 344.8,182.4 "/>
			<rect x="378.9" y="57.1" transform="matrix(0.776 -0.6307 0.6307 0.776 39.3807 284.1144)" width="81.6" height="59.1"/>
			<rect x="451.3" y="60.7" fill="#C6C6C6" width="37.3" height="41.3"/>
			<path fill="#939393" d="M547,31.3H412.6l-68.1,58.9l68.9,58.7H548l65.1-58.1L547,31.3z M403.8,113.2l-26.4-21.5l75-27.6l26.4,22.5
				L403.8,113.2z"/>
			<polygon opacity="0.25" fill="#FFFFFF" enable-background="new    " points="344.6,443.8 413,412.7 548.3,412.7 612.9,386.7 
				612.9,362.5 548.3,388.4 413,388.4 344.6,419.5 "/>
				</g>
			</svg>


			<div class="bev-names">

				<h4><%= link_to b.name, beverage_path(b.id)  %></h4>
				<p>
					<span class="label label-success"><%= Vote.where(beverage_id: b.id, state: "positive").count %></span>
					<span class="label label-default"><%= Vote.where(beverage_id: b.id, state: "meh").count %></span>
					<span class="label label-danger"><%= Vote.where(beverage_id: b.id, state: "negative").count %></span>
				</p>

			</div>
		</div>
	</div>

<% end %>
			
</div>

<div class="row">
	<!-- separates the large amount of cans into smaller more managable groups -->
	<h1><%= will_paginate @beverages, :page_links => false, :next_label => ">", :previous_label => "<", :link_separator => " " %></h1>
	

</div>

<!-- User statistics -->
	<div class="container bev-contain">
			<div class="bev-contain">
				<%=@user.name %>'s Stats
			</div>
		<div class="col-sm-3">
			<h1><%= Beverage.where(user_id: @user.id).count %></h1>
			<div class="bev-names">
				<h3> Bevs Created </h3>
			</div>
		</div>

		<div class="col-sm-3">
			<h1><%= Vote.where(user_id: @user.id).count %></h1>
			<div class="bev-names">
				<h3> Votes Cast </h3>
			</div>
		</div>
		
		<div class="col-sm-3">
			<h1>
				<span class="label label-success"><%= Vote.where(user_id: @user.id, state: "positive").count %></span>
				<span class="label label-default"><%= Vote.where(user_id: @user.id, state: "meh").count %></span>
				<span class="label label-danger"><%= Vote.where(user_id: @user.id, state: "negative").count %></span>
			</h1>
			<div class="bev-names">
				<h3> Vote Distribution </h3>
			</div>
		</div>

		<div class="col-sm-3">
			<h1>PENDING</h1>
			<div class="bev-names">
				<h3> Rank </h3>
			</div>
		</div>
	</div>

<div class="back-button">

	<h4><%= link_to "To Beverages!", beverages_path %></h4>

</div>